### ISSUE TITLE
Интеграция Яндекс музыки в статус Discord

### ISSUE THREAD

**Issue by exotuk** [Stephanzion/YandexMusicBetaMod#10]
Снова здравствуйте, уже скачал новое обновление - работает как часы.

Не думали прикрутить к моду интеграцию с Discord RPC. Я понимаю, что такие проекты есть на гитхабе, но все они требуют либо
установки python, либо node.js, а всё-таки хочется, чтоб всё работало "из коробки" без доп. скриптов и прочего.

А также, есть ли какой-то roadmap по проекту?

**Comment by Stephanzion** [comment]
Добрый вечер. Я правильно понял что речь идет об отображении текущего трека во вкладке "активность" вашего профиля в дискоде?
Роудмапа никакого нет, да и в таких проектах сложно думать наперед, лавочку могут прикрыть в любой момент. Разрабам достаточно проверять наличие плюса не на клиенте, а на сервере)

**Comment by exotuk** [comment]
Да, я говорю о отображении текущего трека в активности Discord.
На счёт роадмапа понял, я думаю, если бы они действительно захотели, то давно бы прикрыли способ обхода, приложение под android уже сколько живёт, и ничего.

**Comment by Stephanzion** [comment]
Хорошо, изучу тему с дискордом когда будет свободное время.
По поводу модов - Яндекс уже где-то с 2021 года удалил все моды (и не только музыки) с 4pda. Так что думаю доберутся до всех как только появится ощутимая аудитория) Десктопная музыка еще даже из беты не вышла, так что пока можно развлекаться)

**Comment by exotuk** [comment]
Хорошо. Продолжаю следить за развитием проекта. Очень рад, что мод на ПК версию появился, а то я устал музыку в ВК слушать)

**Comment by TheKing-OfTime** [comment]
> Я понимаю, что такие проекты есть на гитхабе, но все они требуют либо установки python, либо node.js, а всё-таки хочется, чтоб всё работало "из коробки" без доп. скриптов и прочего.

Вариация мода который не требует никаких дополнительных зависимостей тоже есть https://github.com/TheKing-OfTime/YandexMusicModClient
