### ISSUE TITLE
Error cs:line 180

### ISSUE THREAD

**Issue by sJleng** [Stephanzion/YandexMusicBetaMod#11]
![image](https://github.com/user-attachments/assets/45372d6f-51dd-4f62-85d6-6ab215299c9d)

**Comment by Stephanzion** [comment]
Проверьте пожалуйста, есть ли папка YandexMusic в папке с патчером. Если папка есть, проверьте в ней наличие файла Яндекс Музыка.exe. Ошибка произошла на самом последнем этапе, при попытке создать ярлык на рабочем столе.

**Comment by sJleng** [comment]
> Проверьте пожалуйста, есть ли папка YandexMusic в папке с патчером. Если папка есть, проверьте в ней наличие файла Яндекс Музыка.exe. Ошибка произошла на самом последнем этапе, при попытке создать ярлык на рабочем столе.

Мод работает, однако я использую eng локализацию windows, потому скорее всего патчер не смог найти папку с названием рабочий стол.

**Comment by Stephanzion** [comment]
Нет, патчер берет расположение рабочего стола из переменных среды. Скорее всего это проблема устаревшей библиотеки для создания ярлыка. В будущих релизах переделаю, спасибо за фидбек.
