### ISSUE TITLE
Проблема с Запуском патчера

### ISSUE THREAD

**Issue by noski11** [Stephanzion/YandexMusicBetaMod#12]
Здравствуйте, возникла проблема с запуском патчера, у меня 10 Windows. При запуске ничего не происходит вообще, хотя, как я понял, должен открываться хотя бы браузер с меню авторизации. Подскажите, что делать? Пробовал менять браузеры по умолчанию, но всё равно не помогает. Есть еще вариант, что проблема кроется в том, что у меня на ПК уже есть обычная Яндекс Музыка без мода. Если есть решение, пожалуйста, скажите.🙏

**Comment by Stephanzion** [comment]
Добрый вечер, нет, патчер браузер не открывает, это просто программа которая устанавливает яндекс музыку. Странно, что у вас не появляется окошко с программой, но вероятнее всего это работа антивируса винды или любого стороннего. Попробуйте отключить все, что может помешать запуску и отпишите сработает ли.

**Comment by noski11** [comment]
@Stephanzion, наконец-то решил проблему. Поискал в решенных вопросах и нашел, у меня не был установлен .Net8 теперь все запускается, спасибо за мод👍

**Comment by Stephanzion** [comment]
Уточните пожалуйста, вы качали последнюю версию мода, которая требует установки? Для нее не должен требоваться .net, мне важно знать чтобы исправить эту проблему
