### ISSUE TITLE
Не Устанавливается/Обновляется Яндекс Музыка

### ISSUE THREAD

**Issue by egordel** [Stephanzion/YandexMusicBetaMod#13]
При установке или обновлении в YMP Яндекс Музыки выдаёт такую ошибку:
![изображение_2024-09-23_184437310](https://github.com/user-attachments/assets/ca56978a-6e73-440f-8e4e-a7785262311a)
как я понял заблокировали сервер скачивания.

**Comment by Stephanzion** [comment]
Добрый день, патчер не может удалить папку с прошлой версией Яндекс Музыки. Попробуйте удалить ее вручную

**Comment by egordel** [comment]
Не работает.
При чистой установке патчера и установки яндекс музыки та же проблема

**Comment by egordel** [comment]
При чистой установке без папки с музыкой
![изображение_2024-09-23_212812406](https://github.com/user-attachments/assets/2da17c75-274e-4c16-aab7-2f20503d275c)

**Comment by Stephanzion** [comment]
Ну опять ошибка чтения, только теперь во временную папку. От имени администратора пробовали запускать?

**Comment by egordel** [comment]
Помогло, благодарю!

**Comment by vasek3782** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/666cbd5c-9a04-4b4d-8d2a-9dd8fb7feab3" />

**Comment by vasek3782** [comment]
высвечивается это

**Comment by Stephanzion** [comment]
инструкцию прочитайте на странице загрузки

**Comment by vasek3782** [comment]
не понимаю

**Comment by Stephanzion** [comment]
> весенний билд скачайте и распакуйте

Все написано на странице загрузки

**Comment by vasek3782** [comment]
<img width="828" height="500" alt="Image" src="https://github.com/user-attachments/assets/badda181-49cf-4016-b2d5-70c3c5675c8e" />

**Comment by vasek3782** [comment]
вроде делаю по инструкции , но нечего нету или я что то не понимаю

**Comment by Stephanzion** [comment]
https://github.com/Stephanzion/YandexMusicBetaMod/raw/refs/heads/master/Portable/YandexMusic.7z
