### ISSUE TITLE
Не запускает патчер

### ISSUE THREAD

**Issue by paranoia666228** [Stephanzion/YandexMusicBetaMod#14]
просто напросто не запускает патчер, переустанавливал патчер, комп перезагружал. Нужна ваша помощь

**Comment by Stephanzion** [comment]
Пока не успел разобраться почему, но в некоторых случаях требуется наличие [.net 8](https://dotnet.microsoft.com/ru-ru/download/dotnet/8.0). Попробуйте его установить и отпишите, заработает ли

**Comment by landlord6000** [comment]
Кстати да, в версии без GUI это была проблема, так как он писал, что нужно установить .net в консоль, которую, по логике из ридми, никто читать не должен

**Comment by ITProjectDmitry** [comment]
У меня не запускался просто так. Запустил с правами администратора и всё завелось!

**Comment by Stephanzion** [comment]
Добавил в readme пункт о необходимости запуска от имени админа
