### ISSUE TITLE
Приложение тормозит

### ISSUE THREAD

**Issue by landlord6000** [Stephanzion/YandexMusicBetaMod#15]
Качал месяц назад бета версию старую, там были баги, но если их пофиксить, то работало норм. Сейчас очень клевый GUI, мне нравится, респект, но вот почему-то само приложение стало лагать. Не знаете, в чем проблема может быть?

**Comment by Stephanzion** [comment]
в модах ничего особо лагающего нет, можете попробовать удалить папку %appdata%\YandexMusic, там сессия и кэш приложения хранятся, может станет лучше
