### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sJleng** [Stephanzion/YandexMusicBetaMod#18]
![image](https://github.com/user-attachments/assets/1fed3d61-03ec-4c93-834e-f3fc7766d41d)

**Comment by Stephanzion** [comment]
О проблеме известно, ошибка при создании ярлыка на рабочем столе. Спасибо за информацию, исправлю когда появится время. Скажите, у вас создалась папка YandexMusic в папке с патчером? Если да, вы можете запустить Яндекс Музыку из этой папки и пользоваться как обычно, проблема только в ярлыке.

**Comment by sJleng** [comment]
Я уже репортил эту ошибку в прошлом билде. Потому думал, что уже пофикшено.

**Comment by Stephanzion** [comment]
[Вероятно пофикшено](https://github.com/Stephanzion/YandexMusicBetaMod/releases/tag/v2.0.4#:~:text=%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%20%D0%BC%D0%B5%D1%85%D0%B0%D0%BD%D0%B8%D0%B7%D0%BC%20%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F%20%D1%8F%D1%80%D0%BB%D1%8B%D0%BA%D0%B0) в последних релизах
