### ISSUE TITLE
запускаю файл, ничего не происходит

### ISSUE THREAD

**Issue by asfxdi0** [Stephanzion/YandexMusicBetaMod#2]
при запуске патчера, ничего не происходит

**Comment by Stephanzion** [comment]
> при запуске патчера, ничего не происходит

Только что проверил у себя, патчер работает, после запуска патчера должно появиться окно консоли. Скорее всего, у вас не установлен [.net 8](https://dotnet.microsoft.com/ru-ru/download/dotnet/8.0). Пожалуйста, установите и отпишите заработает ли патчер.

**Comment by asfxdi0** [comment]
> > при запуске патчера, ничего не происходит
> 
> Только что проверил у себя, патчер работает, после запуска должно появиться окно консоли. Скорее всего, у вас не установлен [.net 8](https://dotnet.microsoft.com/ru-ru/download/dotnet/8.0). Пожалуйста, установите и отпишите заработает ли патчер.

все заработало, спасибо огромное

**Comment by asfxdi0** [comment]
только музыка не запускается, стоит на паузе

**Comment by Stephanzion** [comment]
> только музыка не запускается, стоит на паузе

Ранее не сталкивался. Попробуйте выбрать другие секции в меню, запустить мою волну, найти трек через поиск и там запустить. Если не заработает - попробуйте перезапустить. Если не поможет, будем разбираться дальше

**Comment by asfxdi0** [comment]
> > только музыка не запускается, стоит на паузе
> 
> Ранее не сталкивался. Попробуйте выбрать другие секции в меню, запустить мою волну, найти трек через поиск и там запустить. Если не заработает - попробуйте перезапустить. Если не поможет, будем разбираться дальше

ничего из этого не работает(

**Comment by Stephanzion** [comment]
> > > только музыка не запускается, стоит на паузе
> > 
> > 
> > Ранее не сталкивался. Попробуйте выбрать другие секции в меню, запустить мою волну, найти трек через поиск и там запустить. Если не заработает - попробуйте перезапустить. Если не поможет, будем разбираться дальше
> 
> ничего из этого не работает(

Вверху приложения есть вкладка Debug. Далее в списке выберите Toggle Developer Tools, когда откроется, в том же списке нажмите Force Reload. В панели отладки нужно выбрать fetch/xhr, как показал на скрине. Включите любой трек. Высветится список запросов, которые посылает приложение, пришлите их скрин либо самостоятельно проверьте, чтобы  было не более 1 ошибки, выделенной красной строкой.

![image](https://github.com/user-attachments/assets/787da62c-f78a-455b-875e-cf59bdd5730c)

**Comment by asfxdi0** [comment]
https://imgur.com/a/ZXxzrI2

**Comment by asfxdi0** [comment]
![APoxky4](https://github.com/user-attachments/assets/3c4185c2-25bc-4d97-83c1-c5e5dd4d38a8)

**Comment by asfxdi0** [comment]
нажимаю, последняя ошибка

**Comment by asfxdi0** [comment]
> нажимаю, последняя ошибка

в описании ошибки 403 Forbidden

**Comment by Stephanzion** [comment]
> > нажимаю, последняя ошибка
> 
> в описании ошибки 403 Forbidden

Да, это ошибка и она связана с получением трека. Выделите строку с ошибкой, нажмите вверху preview и скиньте текст ошибки из этого окна

![image](https://github.com/user-attachments/assets/e45669d9-3a4a-4604-9cc4-3b43f910be48)

**Comment by asfxdi0** [comment]
![image](https://github.com/user-attachments/assets/30bef343-019a-4ade-810e-7aab5c17e5c1)

**Comment by Stephanzion** [comment]
> ![image](https://private-user-images.githubusercontent.com/91019559/360696433-30bef343-019a-4ade-810e-7aab5c17e5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjY3NjcsIm5iZiI6MTcyNDM2NjQ2NywicGF0aCI6Ii85MTAxOTU1OS8zNjA2OTY0MzMtMzBiZWYzNDMtMDE5YS00YWRlLTgxMGUtN2FhYjVjMTdlNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIyNDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZGNkZTMwMWIxZDRkNzkwYzE1YmFjMDk0MTU4ODdhNDZjM2JmODRhM2VlMjI0NjdlYjA3ZjZjNzZiNTkwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSda9lGn9faosWFq0-VcmQkezvGbFM08Unn4Y4n5Rw8)

Выглядит как проблема с авторизацией. С веб версии или мобильного приложения пробовали музыку слушать с этого аккаунта?

**Comment by asfxdi0** [comment]
> > ![image](https://private-user-images.githubusercontent.com/91019559/360696433-30bef343-019a-4ade-810e-7aab5c17e5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjY3NjcsIm5iZiI6MTcyNDM2NjQ2NywicGF0aCI6Ii85MTAxOTU1OS8zNjA2OTY0MzMtMzBiZWYzNDMtMDE5YS00YWRlLTgxMGUtN2FhYjVjMTdlNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIyNDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZGNkZTMwMWIxZDRkNzkwYzE1YmFjMDk0MTU4ODdhNDZjM2JmODRhM2VlMjI0NjdlYjA3ZjZjNzZiNTkwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSda9lGn9faosWFq0-VcmQkezvGbFM08Unn4Y4n5Rw8)
> 
> Выглядит как проблема с авторизацией. С веб версии или мобильного приложения пробовали музыку слушать с этого аккаунта?

Да, пробовал, там все окей

**Comment by asfxdi0** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/91019559/360696433-30bef343-019a-4ade-810e-7aab5c17e5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjY3NjcsIm5iZiI6MTcyNDM2NjQ2NywicGF0aCI6Ii85MTAxOTU1OS8zNjA2OTY0MzMtMzBiZWYzNDMtMDE5YS00YWRlLTgxMGUtN2FhYjVjMTdlNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIyNDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZGNkZTMwMWIxZDRkNzkwYzE1YmFjMDk0MTU4ODdhNDZjM2JmODRhM2VlMjI0NjdlYjA3ZjZjNzZiNTkwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSda9lGn9faosWFq0-VcmQkezvGbFM08Unn4Y4n5Rw8)
> > 
> > 
> > Выглядит как проблема с авторизацией. С веб версии или мобильного приложения пробовали музыку слушать с этого аккаунта?
> 
> Да, пробовал, там все окей

![image](https://github.com/user-attachments/assets/a5661e50-2e5a-4050-aa30-a669c3dfb04a)

**Comment by Stephanzion** [comment]
честно говоря без идей. Попробуйте пожалуйста нажать на иконку профиля внизу слева и перезайти заново в тот же или другой аккаунт

**Comment by Stephanzion** [comment]
Еще может быть проблема с системными часами, если время на компьютере спешит или отстает будет примерно такая же ошибка. Проверить это можно в настройках даты и времени

**Comment by asfxdi0** [comment]
с новым аккаунтом все работает, но непонятно почему так

**Comment by Stephanzion** [comment]
может со старым тоже заработает и нужно было просто перезайти?

**Comment by asfxdi0** [comment]
Неа, захожу на старый, та же потеха

**Comment by Stephanzion** [comment]
Может впн, прокси используете?

**Comment by asfxdi0** [comment]
> ###
> [Aug 23, 2024](#issuecomment-2305877430)

Если только goodbyedpi для ютуба

**Comment by asfxdi0** [comment]
у меня до этого стояла яндекс музыка на компе без мода, может дело в этом?

**Comment by asfxdi0** [comment]
> у меня до этого стояла яндекс музыка на компе без мода, может дело в этом?

И на ней был введен этот аккаунт

**Comment by Stephanzion** [comment]
> у меня до этого стояла яндекс музыка на компе без мода, может дело в этом?

Маловероятно, особенно если недавно ставили оригинальную яндекс музыку. Но можно на всякий случай почистить кеш по пути `%appdata%\YandexMusic`, только придется заново логиниться. И еще на время можно отключить dpi

**Comment by asfxdi0** [comment]
> > у меня до этого стояла яндекс музыка на компе без мода, может дело в этом?
> 
> Маловероятно, особенно если недавно ставили оригинальную яндекс музыку. Но можно на всякий случай почистить кеш по пути `%appdata%\YandexMusic`, только придется заново логиниться. И еще на время можно отключить dpi

dpi отключил, кеш почистил, все то же самое

**Comment by asfxdi0** [comment]
Ну ладно, думаю это уже проблема в аккаунте, спасибо огромное с остальным!
