### ISSUE TITLE
Не работает подписка после последнего обновления.

### ISSUE THREAD

**Issue by egordel** [Stephanzion/YandexMusicBetaMod#21]
Возникла проблема с тем что после обновления музыки до последней версии, активированная подписка пропадает.
![Снимок экрана 2024-10-17 213549](https://github.com/user-attachments/assets/3ce4da5d-7365-4e87-8c52-0fae41414fd2)
при возможности дайте файлы YandexMusic версии 5.23.1 или 5.23.2.

**Comment by Stephanzion** [comment]
спасибо за информацию, займусь фиксом. Пока файлы скинуть не могу

**Comment by Stephanzion** [comment]
Патчер [снова работает](https://github.com/Stephanzion/YandexMusicBetaMod/releases/tag/v2.0.4)
