### ISSUE TITLE
Кнопка скачать альбом или исполнителя

### ISSUE THREAD

**Issue by Druidblack** [Stephanzion/YandexMusicBetaMod#22]
Добрый день. Есть ли техническая возможность сделать, что бы одной кнопкой можно было скачивать альбом или даже все композиции исполнителя?

**Comment by Stephanzion** [comment]
Добрый вечер, технически возможно. Постараюсь сделать как минимум загрузку альбомов в ближайшее время

**Comment by Stephanzion** [comment]
Скачивание альбомов доступно в [последней версии](https://github.com/Stephanzion/YandexMusicBetaMod/releases/tag/v2.0.5)
