### ISSUE TITLE
Это баг или фича ?

### ISSUE THREAD

**Issue by Koaxz** [Stephanzion/YandexMusicBetaMod#23]
![222222](https://github.com/user-attachments/assets/141d0fed-20bf-4478-9799-444108a2c17c)
![1111111](https://github.com/user-attachments/assets/eac4f8f2-ff37-48f8-ad04-1b0c33676eab)

**Comment by Stephanzion** [comment]
Скачивание трека происходит в том качестве, которое вы выбрали в плеере. Чтобы получить файл меньшего размера выберите качество хуже
