### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Appolon1234** [Stephanzion/YandexMusicBetaMod#26]

**Comment by Stephanzion** [comment]
Предоставьте скриншоты патчера и описание проблемы.

**Comment by Appolon1234** [comment]
завтра

сб, 2 нояб. 2024 г., 22:23 Stepan ***@***.***>:

**Comment by Appolon1234** [comment]
https://i.imgur.com/xKVSwQg.png вот, пытался переустановить, но нечего не поменялось:)

**Comment by Stephanzion** [comment]
Треки включает? По вкладкам переключает? Если ничего из этого не работает переустановите патчер со включенным режимом разработчика, а затем откройте консоль во вкладке Debug вверху приложения. Выберите указанные на скриншоте вкладки а затем нажмите F5 чтобы перезагрузить приложение. Если среди запросов в консоли будут красные строчки, скиньте их скриншот, только замажьте строчку которая начинается с OAuth, это ваш токен авторизации. 

![image](https://github.com/user-attachments/assets/76eccf5a-d21c-4cd8-a34e-da4ba1567bde)
