### ISSUE TITLE
не работает с Vpn

### ISSUE THREAD

**Issue by MSGR04** [Stephanzion/YandexMusicBetaMod#28]
Не работает с VPN, как то пофиксить можно?

**Comment by Stephanzion** [comment]
Посмотрите в настройках вашего впн приложения либо в интернете. Если там есть возможность создать белый список айпи/доменов, то скину вам адреса серверов яндекса, чтобы запросы на них шли напрямую, не через впн.

**Comment by MSGR04** [comment]
Скиньте пожалуйста

**Comment by Stephanzion** [comment]
api.music.yandex.net
music.yandex.net
yandex.net
yandex.ru

Этого должно хватить

**Comment by MSGR04** [comment]
Пофиксил, спс
