### ISSUE TITLE
DiscordRPC

### ISSUE THREAD

**Issue by nist1-scripter** [Stephanzion/YandexMusicBetaMod#29]
Было бы славно, если бы при прослушивании трека на Яндекс.Музыке в дискорде писалось какую именно музыку ты слушаешь, примерно как на Spotify.

**Comment by Stephanzion** [comment]
Вопрос уже [неоднократно](https://github.com/Stephanzion/YandexMusicBetaMod/issues/17) поднимался, есть в планах, но пока нет времени на реализацию( Возможно через месяц-два руки дойдут.
