### ISSUE TITLE
YandexMusicBetaMod x86 на базе Вашей v0.1

### ISSUE THREAD

**Issue by mediaexplorer74** [Stephanzion/YandexMusicBetaMod#3]
Здравствуйте. Имею хобби оч. древние виндуспланшеты юзать. В качестве эха отмененного Майками проекта Андромеда недавно собрал вот зверька (аппарат Qumo 8008w, операционка - последняя x86 бетка Win10/11):
![image](https://github.com/user-attachments/assets/4acc6c86-f44f-4cd9-a839-fa104422605b)

И сколько не выёживался я, пока так и не смог накатить appx-пакет UWP x86 версию Я.Музыки 3.28, не требующей подписки Плюс и вполне себе пашущей UWP ARM варик на моем динозаврофоне Нокия Люмия 950 :)  Поэтому переключил интерес на классич. приложение Я.Музыка v5 бета. На рабочем ноутбуке Ваш YandexMusicBetaMod с операционкой Win11 Lite x64 пашет отлично, спасибо Вам! А вот на 32-битной операционке планшета беда.... (((
Помогите, пожалуйста, по возможности собрать YandexMusicBetaMod x86 на базе Вашего мода v0.1. Так понял, потроха этого проекта состоят из оболочки Electron. Если вдруг у Вас установлена среда разработки под этот Электрон, помогите, пожалуйста, пересобрать всё это счастье под target x32 ;)

С уважением,
  MediaExplorer

**Comment by Stephanzion** [comment]
Добрый день, создал x86 сборку на основе последнего релиза Музыки. Из минусов - вместо оригинальной иконки приложения стоит стандартая иконка электрона, но наверно можно заменить через стороннюю программу. Также не работает расширение, устанавливаемое патчером для блокировки части аналитики, так что некоторые запросы на mc.yandex.ru все равно проходят. В остальном все работает - плюс активен, музыка играет. Тестировал на windows 10 x86 22h2.

https://drive.google.com/file/d/1N6LyhtmHjjOUXCkXwqcjAA1jF1DV-Zpd/view?usp=sharing

**Comment by mediaexplorer74** [comment]
Stephanzion, низкий поклон. Респект и уважуха. Не ожидал, что так быстро переделаете разрядность мода. Про утечку аналитики не беспокоюсь, имею несколько аккаунтов яндекса, включая оооч. древнющий формата @nm.ru, где передача писем давно сломалась и нет спама.
Еще раз спасибо большое.  Всё качнул.  Issue закрываю
