### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by senolfndk** [Stephanzion/YandexMusicBetaMod#31]
😒
![Ekran görüntüsü 2024-11-21 221553](https://github.com/user-attachments/assets/ac5e5f33-e40f-4186-8a31-fac9b19d9f7b)

**Comment by Stephanzion** [comment]
Работает ли воспроизведение музыки, навигация по вкладкам? Есть ли возможность протестировать на другом аккаунте? Does music playback, tab navigation work? Is it possible to test on another account?

**Comment by senolfndk** [comment]
> Peki, müzik dinlemek için ne yapmalı? Peki, bir bankaya gitmek için ne yapmalı? Müzik çalma ve sekmede gezinme çalışıyor mu? Başka bir hesapta test etmek mümkün mü?

Same problem in other account.

**Comment by senolfndk** [comment]
Uploading Kayıt 2024-11-21 224047.mp4…

**Comment by senolfndk** [comment]
https://github.com/user-attachments/assets/4f8e6965-9116-4d10-96ff-6acfb6d773dd

**Comment by Stephanzion** [comment]
I've previously received complaints about the inability to use Yandex Music via VPN from Russian-speaking users. Perhaps it matters where you are trying to access the application from.

Judging by the fact that the app is partially working, there may be a problem with your device. So, I get similar errors when testing the app on older versions of windows 10. Can you specify which build and version of the system you are using?

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2024-11-21 225413](https://github.com/user-attachments/assets/7393490f-66a8-447f-ab65-a18e4f038540)

**Comment by Stephanzion** [comment]
Well, in this case I recommend you to try Russian VPN. If it doesn't work, consider other options.

**Comment by senolfndk** [comment]
I couldn't find it. Can you give me a VPN?

**Comment by senolfndk** [comment]
I couldn't find a VPN for Russia, the ones I found were paid.

**Comment by senolfndk** [comment]
There is nothing to do 😒
![Ekran görüntüsü 2024-11-21 234326](https://github.com/user-attachments/assets/8b04d261-5286-495e-985c-c668e29d3d28)

**Comment by Stephanzion** [comment]
> I couldn't find it. Can you give me a VPN?

I can't find free solutions either, the search is complicated by the fact that most of the VPN clients won't even run on my pc because of my geolocation. 



You can try downloading any free VPN with the largest selection of locations, and then try opening the app from other geo locations in eastern europe.

**Comment by senolfndk** [comment]
I tried in other locations it doesn't work

**Comment by Stephanzion** [comment]
I don't think there's anything else I can do. The only thing left to consider is buying paid VPN/proxy or using another streaming service available in your country

**Comment by senolfndk** [comment]
> Yapabileceğim başka bir şey olduğunu sanmıyorum. Düşünülmesi gereken tek şey ücretli VPN/proxy satın almak veya ülkenizde mevcut başka bir yayın hizmeti kullanmaktır

No problem, thank you for your help.
