### ISSUE TITLE
Фидбек по обновлению v2.0.6

### ISSUE THREAD

**Issue by exotuk** [Stephanzion/YandexMusicBetaMod#32]
Здравствуйте! Проверил Discord RPC - всё работает как часы. (( Обхожу блокировку через утилиту [discord-zapret-youtube](https://github.com/Flowseal/zapret-discord-youtube/) )) Правда при переустановке патчера вылезла ошибка о том, что нужны права администратора, но это мелочи. 

Ещё момент, там функция скачивания треков вошла в релиз, судя по ченджлогу от Яндекса. (( 5.29.3, от 21 ноября ))
Думаю, её можно удалить из патчера.

Спасибо за ваш труд!

**Comment by Stephanzion** [comment]
Добрый день, спасибо за отзыв, рад что с дискодом все работает. 

Скачивание треков и правда теперь доступно из коробки, но это не распространяется на подкасты и аудиокниги( Наверно, стоит подождать пока яндекс допилит эту фичу
