### ISSUE TITLE
Ничего не работает

### ISSUE THREAD

**Issue by dan4ikk1** [Stephanzion/YandexMusicBetaMod#33]
После сегодняшнего обновления ЯМ пишет "не удалось получить часть данных". Кнопки не кликабельны, музыка не запускается
![image](https://github.com/user-attachments/assets/aa4510bb-8d15-40bd-97e9-ae59c2494750)

**Comment by Stephanzion** [comment]
Подробно опишите что пробовали делать и какой результат получили.

**Comment by dan4ikk1** [comment]
> Подробно опишите что пробовали делать и какой результат получили.

Апдейтнул коммент выше, случайно без текста создал

**Comment by Stephanzion** [comment]
Уточните версию и сборку windows, пользуетесь ли ВПН, из какой страны пытаетесь запустить

**Comment by dan4ikk1** [comment]
> Уточните версию и сборку windows, пользуетесь ли ВПН, из какой страны пытаетесь запустить

Без ВПН пользуюсь, местоположение Россия. С ВПН Финляндии такая же ситуация.
![image](https://github.com/user-attachments/assets/4877675d-c82a-4398-88a8-d9b8fab8ac97)

**Comment by Stephanzion** [comment]
Хорошо, поставлю вашу винду на виртуалку и отпишу. На сайт яндекс музыки нормально заходит, там все работает?

**Comment by dan4ikk1** [comment]
> Хорошо, поставлю вашу винду на виртуалку и отпишу. На сайт яндекс музыки нормально заходит, там все работает?

Да, без ВПН на оф. сайт заходит, музыка включается. Спеки ПК нужны? Или, может, патчер логи пишет?

**Comment by Stephanzion** [comment]
Да, давайте посмотрю логи, патчер их пишет в своем окошке. Вообще если впн не стоит то обычно такие баги привязаны к аккаунту и вызваны самим яндексом. Если есть возможность попробуйте зайти с другого

**Comment by dan4ikk1** [comment]
> Да, давайте посмотрю логи, патчер их пишет в своем окошке. Вообще если впн не стоит то обычно такие баги привязаны к аккаунту и вызваны самим яндексом. Если есть возможность попробуйте зайти с другого

Причину выявил - вход в приложение с впн. Лечится только переустановкой патчера. Через браузер музыка пишет, что приложение недоступно в моем регионе, поэтому проблема на стороне яндекса. Благодарю за обратную связь!
