### ISSUE TITLE
Яндекс Музыка

### ISSUE THREAD

**Issue by Sinur21042** [Stephanzion/YandexMusicBetaMod#34]
При скачивании песен, файлы сохраняются с расширением *.mp3, а не с расширением *.flac

**Comment by Stephanzion** [comment]
Спасибо за предложение. Расширение mp3 Яндекс сам присваивает всем аудиофайлам, в независимости от их кодека. Ваш плеер будет воспроизводить флак как флак в любом случае, несмотря на расширение

В будущих обновлениях постараюсь исправить, но пока не в приоритете
