### ISSUE TITLE
не удалось получить часть данных при старте

### ISSUE THREAD

**Issue by balevichh** [Stephanzion/YandexMusicBetaMod#37]
что делать? эта ошибка вылезает при открывании яндекс музыки, и ничего не грузит
![Снимок экрана 2024-12-04 195720](https://github.com/user-attachments/assets/10390483-2ee9-48f7-a6f5-3a0f8b1dc58b)

**Comment by nrksu1tan** [comment]
This happens to me periodically. Just wait a bit

**Comment by Stephanzion** [comment]
это известный баг яндекса, если вкраце - поможет только зайти под другим аккаунтом. Исправить это модом скорее всего можно, но пока не доходят руки

**Comment by balevichh** [comment]
> This happens to me periodically. Just wait a bit

I have had this error for more than a month, I have had it for a long time

**Comment by nrksu1tan** [comment]
> > это известный баг яндекса, если вкраце - поможет только зайти под другим аккаунтом. Исправить это модом скорее всего можно, но пока не доходят руки
> 
> сделал куча акков везде такая ошибка :( видимо нужен русский номер, а у меня польский

Попробуй казахские номера😊

**Comment by balevichh** [comment]
> > > это известный баг яндекса, если вкраце - поможет только зайти под другим аккаунтом. Исправить это модом скорее всего можно, но пока не доходят руки
> > 
> > 
> > сделал куча акков везде такая ошибка :( видимо нужен русский номер, а у меня польский
> 
> Попробуй казахские номера😊

найти бы еще казахский номер..

**Comment by nrksu1tan** [comment]
![image](https://github.com/user-attachments/assets/4e7517f2-2af1-433f-a798-98ea4a3b5d12)
Вот[ здесь ](https://sms-activate.guru/ru)

**Comment by Stephanzion** [comment]
> сделал куча акков везде такая ошибка :( видимо нужен русский номер, а у меня польский

Если у вас есть ненужный аккаунт с этим багом то можете скинуть мне в личку данные для входа, будет проще сделать фикс.
stephanzion@gmail.com / https://t.me/QxPWLO

**Comment by balevichh** [comment]
> > сделал куча акков везде такая ошибка :( видимо нужен русский номер, а у меня польский
> 
> Если у вас есть ненужный аккаунт с этим багом то можете скинуть мне в личку данные для входа, будет проще сделать фикс. [stephanzion@gmail.com](mailto:stephanzion@gmail.com) / https://t.me/QxPWLO

да могу кинуть, ожидайте в течении 15 минут

**Comment by Stephanzion** [comment]
Разобрались, нужен был российский впн
