### ISSUE TITLE
не убирается галочка с "без яндекс плюс"

### ISSUE THREAD

**Issue by narcissist207** [Stephanzion/YandexMusicBetaMod#39]
![YandexMusicPatcherGui_QTC7zvgSGL](https://github.com/user-attachments/assets/76049973-55a9-4f39-b3f1-d76cf03f3e21)

**Comment by Stephanzion** [comment]
Так и должно быть, на данный момент этот мод нельзя отключить. Если у вас уже есть плюс, эта галочка ни на что не повлияет

**Comment by narcissist207** [comment]
а если нет плюса, в чем смысл мода тогда, если нет обхода

**Comment by mediaexplorer74** [comment]
> а если нет плюса, в чем смысл мода тогда, если нет обхода

Показать Яндекс честность и толерантность, при этом получить возможность пользования альтернативным муз. плеером от данного разработчика.
