### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by yyea23** [Stephanzion/YandexMusicBetaMod#40]
Запускаю нажимаю на яндекс музыку, выдаёт ошибку, добавил ниже ошибку, пробовал через запустить администратора не получается, через патчер тоже не получается и обновы
![1](https://github.com/user-attachments/assets/afa0ff24-49ea-433c-bebf-69726072d8c4)
![2](https://github.com/user-attachments/assets/0c947565-8c1d-4ae8-9725-543837e1f985)

**Comment by Stephanzion** [comment]
У вас 32х разрядная windows?

**Comment by yyea23** [comment]
> У вас 32-разрядная версия Windows? Сейчас Яндекс Музыка поставляется только с x64-битной версией

нет, 64

**Comment by Stephanzion** [comment]
Проверьте наличие файла `C:\Program Files\YandexMusicPatcher\YandexMusic\Яндекс Музыка.exe`

**Comment by yyea23** [comment]
> Проверьте наличие файла `C:\Program Files\YandexMusicPatcher\YandexMusic\Яндекс Музыка.exe`

есть такая папка

**Comment by Stephanzion** [comment]
Мне нужно чтобы вы проверили наличие файла. Что в папке? Если в папке пусто - скиньте сюда лог патчера, это текст в нижней части программы

**Comment by yyea23** [comment]
> Мне нужно, чтобы вы проверили наличие файла. Что в папке? Если в папке пусто, сбросьте сюда лог патчера, это текст в нижней части программы
 в папке не пусто, есть файлы

**Comment by yyea23** [comment]
а яндекс музыка в конце это приложение? или папка такая?

**Comment by Stephanzion** [comment]
Яндекс музыка это исполняемый файл exe, находящийся в папке. Если он есть - попробуйте его запустить напрямую из папки

**Comment by yyea23** [comment]
Та же ошибка вылазит

**Comment by Stephanzion** [comment]
Значит скорее всего проблема в том, что у вас windows 7. Рекомендую установить официальную Яндекс Музыку и попробовать ее запустить, чтобы убедиться в этом
