### ISSUE TITLE
Не работает обход плюса 

### ISSUE THREAD

**Issue by InsanE-from-DC** [Stephanzion/YandexMusicBetaMod#41]
При запуске патчера запускается обычная яндекс музыка без плюса и ничего не происходит

**Comment by Stephanzion** [comment]
Пришлите логи патчера после установки мода

**Comment by InsanE-from-DC** [comment]
где их можно найти?

**Comment by Stephanzion** [comment]
это текст над кнопкой установить мод, сведения об установке

**Comment by InsanE-from-DC** [comment]
не могу найти

**Comment by Stephanzion** [comment]
![](https://github.com/user-attachments/assets/4ac4f3c4-1af5-437a-a5d1-461562755c87)

**Comment by InsanE-from-DC** [comment]
![image](https://github.com/user-attachments/assets/659b9023-0b36-441e-87a2-384190c351de)

**Comment by Stephanzion** [comment]
> Пришлите логи патчера **после установки мода**

**Comment by Stephanzion** [comment]
Также ознакомьтесь со [списком стран](https://yandex.ru/support/music/ru/access.html) в которых доступна яндекс музыка, у многих такая проблема

**Comment by InsanE-from-DC** [comment]
по стране подхожу

**Comment by InsanE-from-DC** [comment]
![image](https://github.com/user-attachments/assets/d6dd4e0a-05fe-46fc-9865-30e137325346)

**Comment by Stephanzion** [comment]
Выглядит нормально. Впн отключен? После авторизации что показывает?

**Comment by InsanE-from-DC** [comment]
впн отключен, а регистрации не было сразу перекинуло в аккаунт
![image](https://github.com/user-attachments/assets/b193925d-388d-4fd1-a11f-11a5a8b81350)

**Comment by Stephanzion** [comment]
Что не работает то тогда?

**Comment by InsanE-from-DC** [comment]
обход плюса

**Comment by Stephanzion** [comment]
выражается это в чем?

**Comment by InsanE-from-DC** [comment]
ну на скриншоте видно доступна только вкладка коллекци, а самой яндекс музыкой как таковой нельзя пользоваться

**Comment by Stephanzion** [comment]
веб версия яндекс музыки работает? [Скачивать](https://github.com/Stephanzion/YandexMusicBetaMod/raw/refs/heads/master/Portable/YandexMusic.7z) стабильный билд пробовали?

**Comment by InsanE-from-DC** [comment]
стабильная версия все тоже самое дает

**Comment by InsanE-from-DC** [comment]
странно что сразу же закидывает в аккаунт хотя я не вводил данные

**Comment by InsanE-from-DC** [comment]
в веб версию я не заходил

**Comment by InsanE-from-DC** [comment]
а каким образом это повлияет

**Comment by Stephanzion** [comment]
Проверить доступность яндекса

**Comment by InsanE-from-DC** [comment]
сам яндекс у меня работает аккаунт есть

**Comment by InsanE-from-DC** [comment]
есть возможность сделать так чтобы заново сделать чтобы была страница входа потому что я запускаю приложение и мне просто аккаунт мой показывает и как будто дефолт яндекс музыка без плюса

**Comment by Stephanzion** [comment]
можно выйти из аккаунта нажав на аватарку. Откройте в брауезре у себя https://music.yandex.ru/home

**Comment by InsanE-from-DC** [comment]
зашел, на веб версию все хорошо, но до сих пор меня закидывает в аккаунт сразу и ничего нет

**Comment by Stephanzion** [comment]
Ну явные проблемы с гео, наверняка или впн, или прокси или изначальное местоположение не из белого списка яндекса. Стабильный билд точно должен был заработать. Все что могу теперь посоветовать - оформить яндекс плюс за 1р на виртуальную карту, чтобы не было автосписаний и попробовать зайти в официальный клиент яндекс музыки. Вероятность 99 процентов что даже так работать не будет. В случае оставшегося 1 процента - обещаю дополнительно разобраться.

**Comment by InsanE-from-DC** [comment]
только что так и сделал оформлял яндекс плюс на другой аккаунт но когда заходил в приложение показывает тот же аккаунт и ничего

**Comment by Stephanzion** [comment]
ну я же уже писал как сменить аккаунт. Тем более для эксперимента нужно заходить с официального клиента яндекс музыки с их сайта.

**Comment by Stephanzion** [comment]
как в итоге решили вопрос?
