### ISSUE TITLE
вин 10. кнопки сворачивания в оконном режиме

### ISSUE THREAD

**Issue by wugenz** [Stephanzion/YandexMusicBetaMod#42]
ну ладно... кароче, в ситуации проебавшейся флешки с 11 виндой при смене ссдшника я проебался и теперь я пока посижу на 10. так, это неважно. важно вот что... после установки мода я как всегда на 11 винде сидел в оконном режиме твоего шедевромода и тут незадача. я блять не могу свернуть и развернуть на полный экран окно. ну я по дефолту навожусь на кнопки и они блять не выделяются, ну и ясен хуй они не работают если на них нажать.

сорян, так как стандартный скрин винды убирает курсор со скрина, я лучше ничего не придумал и сделал самый тупой и банальный вариант сфоткал экран с телефона)

![image](https://github.com/user-attachments/assets/4fa8feb8-9b1b-48c8-8f32-f0a2bb49d99c)
 вот смотри, тут видишь выделяется да?
 
 
 
![image](https://github.com/user-attachments/assets/4625e801-3fb9-4069-ab97-1cdad325246a)
![image](https://github.com/user-attachments/assets/55216be5-7b38-4561-8510-e762cd558fab)
а вот тут нет. ну и как я уже писал они не кликабельны.

**Comment by Stephanzion** [comment]
Скачайте официальное приложение яндекс музыки и попробуйте покликать кнопки там, в аккаунт можно не заходить. Если там будет работать а в моде нет - попробую разобраться. Вообще мод никак эти кнопки не трогает, так что проблема скорее всего в чем то другом

**Comment by wugenz** [comment]
> Скачайте официальное приложение яндекс музыки и попробуйте покликать кнопки там, в аккаунт можно не заходить. Если там будет работать а в моде нет - попробую разобраться. Вообще мод никак эти кнопки не трогает, так что проблема скорее всего в чем то другом

ну смотри, если я скачаю с сайта, то твой мод заменится на то что я скачаю. при установке винды у меня автоматом скачалась я музыка из майкрософт стора, там все работает... да и та яндекс музыка впринципе не притендует на то что твой мод существует у меня. а то что с сайта оно заменит мод... по крайней мере на 11 винде было так

**Comment by Stephanzion** [comment]
не должно офиц приложение заменять мод, оно по другому пути устанавилвается. Если совсем проблема с кнопками нерешаемая - можете переустановить мод поставив галку на "включить режим разработчика", тогда кнопки будут стандартные виндовские

**Comment by wugenz** [comment]
> не должно офиц приложение заменять мод, оно по другому пути устанавилвается. Если совсем проблема с кнопками нерешаемая - можете переустановить мод поставив галку на "включить режим разработчика", тогда кнопки будут стандартные виндовские

понял. спасибо, завтра посмотрим
