### ISSUE TITLE
Резервная копия предыдущей версии YM.

### ISSUE THREAD

**Issue by egordel** [Stephanzion/YandexMusicBetaMod#44]
При обновлении в патчере автоматически удаляется старая версия Яндекс Музыки.
Есть идея сделать опцию включения сохранения предыдущей версии.
Если возникнет проблема с новой версией можно будет откатиться до предыдущей версии.
Сделать индикацию версии в патчере чтобы видеть какая версия установлена.

**Comment by Stephanzion** [comment]
Спасибо за идею, возможно в будущем просто сделаю выбор версии яндекс музыки которая будет установлена.

А вообще у меня настроены уведомления на выход новых версий музыки, так что я почти всегда сразу их тестирую и в случае чего буду готов сделать патч.

В целом обновления пока ничего не ломали.
