### ISSUE TITLE
Как убрать режим разработчика

### ISSUE THREAD

**Issue by exotuk** [Stephanzion/YandexMusicBetaMod#5]
Ещё раз здравствуйте, не подскажите, как можно выключить режим разработчика? А то не хочется видеть сразу две панели для закрытия, свертывания/развёртывания приложения (( Надеюсь нормально выразился, на всякий случай прикреплю скриншот того, что я хочу убрать ))
![image](https://github.com/user-attachments/assets/6db6248e-d190-4a0e-92eb-d020189e46dd)

**Comment by Stephanzion** [comment]
Добрый день, на днях выпущу большое обновление, где будет убрана программная панель приложения с кнопками закрыть, свернуть и так далее, останется только виндовая (она на скрине выше, дублирует нижние кнопки). При этом панель с надписью debug останется. Скажите, такой вариант вам подойдет?

**Comment by exotuk** [comment]
Отлично, буду ждать обновления)
