### ISSUE TITLE
Не работают тексты песен

### ISSUE THREAD

**Issue by exotuk** [Stephanzion/YandexMusicBetaMod#6]
И снова здравствуйте, тут такое дело, нельзя посмотреть тексты песен, пишет, что нужна подписка.
Возможно ли добавить возможность просматривать тексты? 
![image](https://github.com/user-attachments/assets/81bd8de2-fa60-464e-bef7-5faa83a2dc7b)

**Comment by Stephanzion** [comment]
Добрый вечер, к сожалению эту функцию невозможно реализовать модом. Возможно, в будущем сделаю возможность подгрузки текста с других сервисов.
