### ISSUE TITLE
Фидбек по обновлению

### ISSUE THREAD

**Issue by exotuk** [Stephanzion/YandexMusicBetaMod#8]
Здравствуйте, даю небольшой фидбек по обновлению!
В целом всё отлично, но есть парочку замечаний:
1.  Эффект при нажатии кнопки скачивания будто клонит влево, по-хорошему бы его отцентровать относительно самой иконки скачки ( если это возможно, конечно же )
2. Я считаю, что решение добавить белую тему в мод странное, т.к она спокойно меняется через настройки в самом приложении.
На этом из минусов пока всё.

Теперь на счёт возможности просмотра текста песни:
Большинство стриминговых сервисов используют сервис Musixmatch (( Spotify, Apple Music, Deezer, да и сама Яндекс.. Музыка ))
У этого сервиса есть свой API, было бы славно прикрутить его к моду, дабы все функции полноценно работали.
(( Также есть LyricsFind, который использует VK, но там значительно меньше текстов, да и API я по первой ссылке в гугле не нашел ))

Спасибо за ваш труд.

**Comment by Stephanzion** [comment]
Добрый вечер, про настройку светлой темы не знал, уберу этот пункт. Касательно того, что кнопка съезжает, можете скрин прикрепить?

**Comment by Stephanzion** [comment]
все, понял о чем вы. Значек загрузки криво вращается) Спасибо за фидбек

**Comment by exotuk** [comment]
На здоровье)
