### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by DemonKingStudio** [Stephanzion/YandexMusicBetaMod#9]
Зачем обязательно добавлять верхнюю панель с утилитами и дебагом вместе с включением инструментов разраба, тк они работают и без этой панели нажатием Ctrl + Shift + I. Можно вывести отмену скрытия этой панели в отдельный пункт.

Посидев в отладке приложения Яндекс Музыки на Windows, оригинальной Яндекс музыки на Android и патченной Яндекс музыке на Android. Я заметил, что генерация sign ключа передаваемого в параметрах Fetch-запроса для получения "текстомузыки" вроде вообще не зависит от аккаунта, а от аккаунта зависит только ключ передаваемый в Headers и имеющий логичное название "Authorization", который в патченной Android версии приложения постоянно равен определенному значению( видимо аккаунта с "Плюсом" ). Можно попробовать подставлять этот токен в запрос на текст( точнее получения ссылки на текст на приватном сервере )

**Comment by Stephanzion** [comment]
Добрый день, не уверен что есть необходимость убирать верхнюю панель тк она доступна только при активном моде "включить консоль разработчика". Обычным пользователям она не помешает, а тем, кто не знает про хоткей запуска devtools она будет полезна.

Касательно ключа в патченой яндекс музыке для андройда - не знал что кто-то просто оставит свой токен авторизации прямо в моде. Если вы его нашли - отправьте пожалуйста его мне на почту stephanzion@gmail.com. Если это будет работать - добавлю в мод. Учитывая предыдущие идеи по разблокировке текстомузыки - этот был бы самым простым и удобным.
